### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by haesleinhuepf** [kephale/napari-tyssue#2]
Hi @kephale ,

just a quick question regarding licensing: [tyssue is GPL-licensed](https://github.com/DamCB/tyssue/blob/master/LICENSE). I'm wondering if napari-tyssue needs to be GPL-licensed as well. I'm hitting such issues quite often and wonder how you deal with these.

Thanks!

Best,
Robert

**Comment by kephale** [comment]
Arg oh goodness you're right. This case needs to be GPL license because it adapts GPL scripts from tyssue. However, I might just GPL those 2 modules (and perhaps eventually factor them out). 

I certainly want all of this to be open source, but GPL frustrates me so much and dealing with this issue doesn't feel like the most productive use of time, even if it is important and essential.

**Comment by kephale** [comment]
Ok actually, the situation isn't that bad. The the code that was adapted came from https://github.com/DamCB/tyssue-demo and https://github.com/suzannelab/invagination, both of which are MPLv2. So actually the current situation is OK, but I'll add more details since I'm partway through anyway.

**Comment by kephale** [comment]
To avoid making a legal answer, since I'm really not a pro at this, I will point to the example set by the tyssue team, where they licensed their demo code under MPLv2, regardless of tyssue's GPL status.

**Comment by haesleinhuepf** [comment]
> I certainly want all of this to be open source, but GPL frustrates me so much

I ♥️ you for this reply. I feel exactly the same 🙌🙂
